---

- name: setup wazuh manager
  block:
    - shell: "curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg"
      become: yes
    - shell: 'echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list'
      become: yes
    - apt: update_cache=yes
      become: yes
    - apt: name="wazuh-manager=4.5.4-1" state=present
      become: yes
    - systemd: name=wazuh-manager enabled=yes masked=no daemon_reload=yes state=restarted
      become: yes

- name: check it has started successfully or fail deployment
  block:
    - command: systemctl is-active wazuh-manager
      register: results
    - assert:
        that:
          - "'active' in results.stdout"

